x-db-env: &db_env
  POSTGRES_USER: ${POSTGRES_USER:-simplefin_to_maybe}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-simplefin_to_maybe}
  POSTGRES_DB: ${POSTGRES_DB:-simplefin_to_maybe}
  TZ: ${TZ:-America/Chicago}

x-rails-env: &rails_env
  <<: *db_env
  SECRET_KEY_BASE: ${SECRET_KEY_BASE}
  RAILS_FORCE_SSL: ${RAILS_FORCE_SSL:-false}
  RAILS_ASSUME_SSL: ${RAILS_ASSUME_SSL:-false}
  DB_HOST: db
  DB_PORT: 5432

services:
  web:
    container_name: simplefin_to_maybe
    image: ghcr.io/steveredden/simplefin_to_maybe:latest
    volumes:
      - app-storage:/rails/storage
    ports:
      - 9501:3000
    restart: unless-stopped
    environment:
      <<: *rails_env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: simplefin_to_maybe-db
    image: postgres:16.8
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      <<: *db_env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  app-storage:
  postgres-data: