---
services:
  db:
    container_name: db
    restart: unless-stopped
    image: postgres:16.8
    networks:
      - simplefinmaybe
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - sf-to-maybe-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: simplefin-to-maybe
    restart: unless-stopped
    build: .
    depends_on:
      - db
    networks:
      - simplefinmaybe
    ports:
      - "9501:3000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      RAILS_ENV: production
      GOOD_JOB_EXECUTION_MODE: async
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app
  
  worker:
    container_name: worker
    restart: unless-stopped
    build: .
    command: ["sh", "-c", "until nc -z db 5432; do sleep 1; done; bundle exec good_job start"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - simplefinmaybe
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: db
      DB_PORT: 5432

networks:
  simplefinmaybe:

volumes:
  sf-to-maybe-data: